# Generated by Django 5.0.1 on 2024-02-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
