# Generated by Django 5.0.1 on 2024-02-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_details_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='user_id',
        ),
    ]
