# Generated by Django 5.0.1 on 2024-02-05 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_order_details_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_prices',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_id', to='shop.product')),
                ('product_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proud_price', to='shop.product')),
            ],
        ),
    ]
