# Generated by Django 5.0.1 on 2024-02-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_prices',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
