# Generated by Django 5.0.1 on 2024-01-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_object_user_product_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_list',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
